[default]
src = 'contracts/BIFI'
test = 'test'
out = 'artifacts'
libs = ['node_modules']
remappings = [
    '@chainlink/=node_modules/@chainlink/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin-2/=node_modules/@openzeppelin-2/contracts/',
    '@openzeppelin-4/=node_modules/@openzeppelin-4/contracts/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@solidity-parser/=node_modules/truffle-flattener/node_modules/',
    '@uniswap/=node_modules/@uniswap/',
    'contracts/=node_modules/@uniswap/lib/contracts/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'prettier-plugin-solidity/=node_modules/abi-to-sol/node_modules/prettier-plugin-solidity/',
]
# libraries = []
# cache = true
force = true
# evm_version = 'london'
# gas_reports = ['*']
## Sets the concrete solc version to use, this overrides the `auto_detect_solc` value
# solc_version = '0.8.10'
auto_detect_solc = true
# offline = false
optimizer = true
optimizer_runs = 200
verbosity = 3
# ignored_error_codes = []
# fuzz_runs = 256
# ffi = false
# sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
# tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
# initial_balance = '0xffffffffffffffffffffffff'
# block_number = 0
# gas_limit = 9223372036854775807
# gas_price = 0
# block_base_fee_per_gas = 0
# block_coinbase = '0x0000000000000000000000000000000000000000'
# block_timestamp = 0
# block_difficulty = 0

# These^ are all the available config options

# Docs at https://github.com/gakonst/foundry/tree/master/config